### PR TITLE
Added initial commands in gitpod

### PR DESCRIPTION
**Pull request by email2vimalraj**
Added gitpod configuration which enables anyone to contribute with zero setup in their local machine.
Just open the repo on the gitpod and start coding.

Refer more about gitpod [here](https://www.gitpod.io/).

### CODE REVIEW

**Comment by thchia** [comment]
This is interesting. How about specifying environment variables, which is necessary to run the project?

**Comment by email2vimalraj** [comment]
There are many ways: more here https://www.gitpod.io/docs/47_environment_variables/

I’m personally set up the required environment variables in my accounts page

**Comment by thchia** [comment]
Lol Guess I should have RTFM 😂

**Comment by wgao19** [comment]
looks interesting, i need rtfm too 😆 shall we merge now?

**Comment by thchia** [comment]
Yes!

**Pull request merged**
