### PR TITLE
[Do Not Merge] Airtable Test

### PR DESCRIPTION
**Pull request by thchia**
Just checking to see if the lambda is working.

### CODE REVIEW

**Comment by thchia** [comment]
Apparently airtable is down...

**Comment by wgao19** [comment]
LOL

**Comment by thchia** [comment]
Airtable is back up, but my code is not working... I will try again tomorrow.

**Comment by thchia** [comment]
Omg that fixed it... Ok I'm closing this for now and will carry on/clean up.

**Pull request closed without merging**
