### PR TITLE
Revert "Revert "Feature/GitHub auth""

### PR DESCRIPTION
**Pull request by wgao19**
Reverts react-knowledgeable/rk-community-site#99

After merging #97 and changing the oauth redirect address, redirect works fine, but it does not display as logged in after the redirect.

Since I could not quickly figure out what was happening, I reverted the merge. Then revert the revert is the fastest way I figured out to get another preview up. Now that the redirect URL pointing at this PR's preview address, and it's working fine.

Very dubious

### CODE REVIEW

**Comment by thchia** [comment]
Weird. I’ll take a look at this over the next few days.

**Comment by thchia** [comment]
Just to confirm, this behaviour you observed roughly matches the following:

- Navigate to `reactknowledgeable.org`
- Scroll down to "Log in with Github"
- Click and authenticate
- Get redirected back to `reactknowledgeable.org`
- Still says "Log in with Github"

**Comment by wgao19** [comment]
Correct

**Comment by thchia** [comment]
I'm going to refactor this in a bit more depth now that I have a better understanding on how to structure function code.

**Pull request closed without merging**
