### PR TITLE
wip: enable concurrent react (again)

### PR DESCRIPTION
**Pull request by wgao19**

### CODE REVIEW

**Comment by thchia** [comment]
Free London wifi can’t merge for some reason :(

**Comment by wgao19** [comment]
don't worry, i think i just found the cause of duplicated render, but i don't fully understand.. seems that calling `ReactDOM.hydrate(/** whatever that was supposed to be rendered */)` removes the duplicate.

**Comment by thchia** [comment]
I actually don’t know what the level of support for concurrent mode in SSR is. I don’t think it’s supported though so we may see strange stuff 🤷‍♀️

**Comment by wgao19** [comment]
hmm, looks like now local build is broken 🤦🏻‍♀️

**Comment by wgao19** [comment]
aight, im gonna merge this

**Comment by wgao19** [comment]
relates to #70

**Pull request merged**
